### ISSUE TITLE
changesets per hour graph time axis

### ISSUE THREAD

**Issue by harry-wood** [jenningsanderson/osmdown#15]
Not sure if this is the right repo for this issue.
Looking at this page http://osm.townsendjennings.com/nepal/ changesets per hour graph. The time axis is all munged together.  Can't tell if the graph goes back to when the earthquake struck

**Comment by jenningsanderson** [comment]
Hi @harry-wood 
Sorry for the tardiness of this response -- I changed that axis a few days ago; and yes, this is the right repository for the display data.

That timeline is being pulled from here: https://github.com/Project-EPIC/osmdown/blob/master/templates/_charts/linegraph_simple.html
